###TBD 
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Chart.Name }}
#   labels:
#     app: {{ .Chart.Name }}
#     chart: {{ .Chart.Version }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# type: Opaque
# data:
#   {{- $files := .Files }}
#   {{- range tuple "secret.yml" }}
#     {{ $files.Get . | nindent 2  }}
#   {{- end }}
